[package]
name    = "curl-inject-opt"
version = "0.2.0"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"Fizyr B.V.",
]
edition = "2018"
license = "BSD-2-Clause"

[dependencies]
curl-inject-opt-shared = { path = "../shared" }

clap      = "2.32.0"
libc      = "0.2.48"
structopt = "0.3.13"
yansi     = "0.5.0"
