[package]
name    = "curl-inject-opt"
version = "0.2.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"
license = "BSD-2-Clause"

[dependencies]
curl-inject-opt-shared = { path = "../shared" }

ansi_term = "0.11.0"
libc      = "0.2.48"
clap      = "2.32.0"
structopt = "0.2.14"
