[package]
name    = "curl-inject-opt-shared"
version = "0.2.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"
license = "BSD-2-Clause"
build   = "build.rs"

[dependencies]
curl-sys = "0.4.16"
