[package]
name    = "curl-inject-opt-shared"
version = "0.2.2"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"Fizyr B.V.",
]
edition = "2021"
license = "BSD-2-Clause"
build   = "build.rs"

[dependencies]
curl-sys = "0.4.16"
