[package]
name    = "curl-inject-opt-preload"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"
license = "BSD-2-Clause"

[lib]
crate-type = ["cdylib"]

[dependencies]
curl-inject-opt-shared = { path = "../shared" }
libc      = "*"
curl-sys  = "*"
